### ISSUE TITLE
Error by startup "function ghci#process#start[5]..ghci#process#initialize"

### ISSUE THREAD

**Issue by maxdore** [owickstrom/neovim-ghci#10]
I would like to use this lovely plugin, but can't start it up. When executing GhciOpen, the plugin fails with 
`py import sys` is not installed in this version

cabal 1.24.0.2 is installed.  Is anyone else experiencing this issue? Or do you have any hints what could cause this?

**Comment by simbuerg** [comment]
The same error pops up when using this plugin from 'vim'. Are you sure you are using neovim, not vim?

**Comment by erik-feller** [comment]
You also can get this error if you installed the incorrect version of the neovim interface via pip. You might need to install the python2 or python3 version depending on which one you don't have.

**Comment by maxdore** [comment]
@erik-feller Thank you that was it.
