### ISSUE TITLE
All commands report that GHCI is still starting up

### ISSUE THREAD

**Issue by erik-feller** [owickstrom/neovim-ghci#11]
After loading completely GhciEval cannot run because GHCI is supposedly still starting but the repl terminal shows that it has completely loaded.

`Error detected while processing function ghci#repl#eval:`
`line    2:`
`GHCi is still starting up...`

**Comment by kozross** [comment]
I get this error too.

**Comment by owickstrom** [comment]
Could you both paste the GHCi terminal contents you have when the error occurs?

**Comment by zmactep** [comment]
The same problem is present for me.
<img width="1440" alt="nvim-haskell" src="https://user-images.githubusercontent.com/1034785/33928016-5b933efa-dff5-11e7-85ae-0c0430466b02.png">

**Comment by owickstrom** [comment]
Hi! I'm deprecating this project in favor of its upstream, `intero-neovim`, which now [has support for using any GHCi backend](https://github.com/parsonsmatt/intero-neovim#using-a-custom-backend). The issue tracker will be closed, but the repository will stay for a while until people have had time to migrate away. If you're experiencing the same issue with intero-neovim, please repost the issue there. Thank you!
