### ISSUE TITLE
Fails to leave start phase if project isn't building

### ISSUE THREAD

**Issue by theNerd247** [owickstrom/neovim-ghci#13]
I'm having this issue with intero-vim as well...

If I open a new stack project that has broken code this plugin doesn't restart: 

```
Error detected while processing function ghci#repl#reload:                                                                                                                                    
line    2:                                                                                                                                                                                    
GHCi is still starting up...    
````

**Comment by theNerd247** [comment]
I can however `:GhciOpen` and view the ghci terminal as well as run `:reload` and it works.

**Comment by owickstrom** [comment]
Hi! I'm deprecating this project in favor of its upstream, `intero-neovim`, which now [has support for using any GHCi backend](https://github.com/parsonsmatt/intero-neovim#using-a-custom-backend). The issue tracker will be closed, but the repository will stay for a while until people have had time to migrate away. If you're experiencing the same issue with intero-neovim, please repost the issue there. Thank you!
