### ISSUE TITLE
Error detected while processing function ghci#process#start[5]..ghci#process#ini tialize

### ISSUE THREAD

**Issue by mark-schultz** [owickstrom/neovim-ghci#14]
When I enable this package, I get the following error upon opening any .hs file:

    Error detected while processing function ghci#process#start[5]..ghci#process#initialize:
    line   13:
    E117: Unknown function: provider#python#Call
    Press ENTER or type command to continue

I've localized the issue to this package. Searching this error leads to [this issue](https://github.com/neovim/neovim/issues/3577) with neovim, which occurs when you don't have the `neovim` python package installed. I both appear to have this package installed:

    $ pip install neovim
    Requirement already satisfied: neovim in ./.local/lib/python3.6/site-packages
    Requirement already satisfied: msgpack-python>=0.4.0 in ./.local/lib/python3.6/site-packages (from neovim)
    Requirement already satisfied: greenlet in ./.local/lib/python3.6/site-packages (from neovim)`

Additionally, my other python-dependent packages (like jedi-python) appear to be working fine.

**Comment by owickstrom** [comment]
Hi! I'm deprecating this project in favor of its upstream, `intero-neovim`, which now [has support for using any GHCi backend](https://github.com/parsonsmatt/intero-neovim#using-a-custom-backend). The issue tracker will be closed, but the repository will stay for a while until people have had time to migrate away. If you're experiencing the same issue with intero-neovim, please repost the issue there. Thank you!
