### ISSUE TITLE
Use :type-at and :loc-at if available

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/neovim-ghci#2]
Since GHC 8.0.1, GHCi has a somewhat hidden support for `:loc-at` and `:type-at`. We could probably use those if available, and fallback to regular `:type` for older versions of GHCi. Would probably make sense to check the GHCi version in the `ghci_initialize` function.

**Comment by parsonsmatt** [comment]
If you want to steal the implementation from [`intero-neovim`](https://github.com/parsonsmatt/intero-neovim), feel free :)

**Comment by owickstrom** [comment]
@parsonsmatt Thanks! :) I'm actually doing just that right now, at least parts of it!
