### ISSUE TITLE
Quickfix integration buggy for multi-line errors

### ISSUE THREAD

**Issue by adelbertc** [owickstrom/neovim-ghci#3]
Seems like for multi-line error messages the plugin will populate the quickfix buffer with the message as-is, which means for an N-line long error message (Neo)Vim thinks there are N errors. For example if the error message is (snipped):

```haskell
Main.hs:18:5: error:
    • Couldn't match type ‘b1’ with ‘Zipper g b'0 a'0’
      ‘b1’ is a rigid type variable bound by
        the type signature for:
          fmap :: forall a b1. (a -> b1) -> Zipper g b a -> Zipper g b b1
        at Main.hs:16:3
```

The quickfix buffer thinks the following are errors (numbered):

1. || [1 of 1] Compiling Main ( Main.hs, interpreted ) 
2. Main.hs|18 col 5 error| error: • Couldn't match type ‘b1’ with ‘Zipper g b'0 a'0’
3. || ‘b1’ is a rigid type variable bound by 
4. || the type signature for:
5. || fmap :: forall a b1. (a -> b1) -> Zipper g b a -> Zipper g b b1 
6. || at Main.hs:16:3

**Comment by owickstrom** [comment]
Pull request in #4.
