### ISSUE TITLE
Allow users to set targets

### ISSUE THREAD

**Issue by parsonsmatt** [owickstrom/neovim-ghci#5]
We have a big Stack project at work, with something like 20 potential stack targets. Some of these have incompatible GHC flags (mostly default extensions, NoImplicitPrelude, etc), and loading all the packages at once breaks GHCi.

Additionally, loading ~34K lines of code is quite a bit slower than loading ~2Kloc and depending on compiled stuff for the rest.

Allowing the users to set the GHCi targets would allow it to be used in larger projects like that.

(Not sure if this is in scope of the intended use of the plugin :smile:  )

**Comment by owickstrom** [comment]
Based on our discussion on Slack, making an effort to generalize intero-neomvim will be the way forward, effectively merging these two projects back together. 👍 So, I'm closing this.
