### ISSUE TITLE
Ability to specify per-project GHCi command

### ISSUE THREAD

**Issue by adelbertc** [owickstrom/neovim-ghci#7]
Currently it seems you have to specify a global one, but this can get tricky if you have different projects some of which use Cabal (+ Nix), some which use Stack. I've also hit issues where I set it to be `cabal repl` but for some projects that have multiple targets `cabal repl` complains about there being multiple targets so I end up having to temporarily set `cabal repl exe:foo` or something.

Perhaps one option is to do something similar to [GHCid](https://github.com/ndmitchell/ghcid/tree/master/plugins/nvim#usage) and let there be a `-c` flag to `:GhciStart`

**Comment by owickstrom** [comment]
There is a section in the readme, perhaps a bit hidden under the Stack section, that shows how you can do project-specific commands. Would this work for you?

**Comment by owickstrom** [comment]
This is a bit related to issue #1, where you can override the command when running :GhciStart.

**Comment by adelbertc** [comment]
Ah yeah that would work, though there is an inconvenience of having it now as a file in the project which you'd have to add to gitignore. 

But yeah this is definitely a duplicate of #1 so closing in favor of that.
