### ISSUE TITLE
GhciLoadCurrentFile fails on some characters of ghci prompt.

### ISSUE THREAD

**Issue by frostyrock** [owickstrom/neovim-ghci#8]
> Error detected while processing function ghci#repl#load_current_file:
> line    2:
> GHCi is still starting up...
> Press ENTER or type command to continue

My default prompt  for ghci  was "\ESC[1;34m𝞴= \ESC[0;m" (displayed as 𝞴= in blue color)
and I changed it to default then command was successful.

**Comment by owickstrom** [comment]
`let g:ghci_prompt_regex = '[^-]> '` is the default for recognizing the prompt. Could you try overriding that to match your custom prompt?

**Comment by owickstrom** [comment]
Hi! I'm deprecating this project in favor of its upstream, `intero-neovim`, which now [has support for using any GHCi backend](https://github.com/parsonsmatt/intero-neovim#using-a-custom-backend). The issue tracker will be closed, but the repository will stay for a while until people have had time to migrate away. If you're experiencing the same issue with intero-neovim, please repost the issue there. Thank you!
