### ISSUE TITLE
Breaks local configs via vim-localvimrc

### ISSUE THREAD

**Issue by kozross** [owickstrom/neovim-ghci#9]
Identical to [this issue][1] in the upstream.

[1]: https://github.com/parsonsmatt/intero-neovim/issues/107

**Comment by owickstrom** [comment]
I see. Is using an (.nvim.rc file)[https://andrew.stwrt.ca/posts/project-specific-vimrc/) an option for you?

Otherwise, do you get any error message when the file doesn't load?

**Comment by kozross** [comment]
Using a ``.nvimrc`` works fine. I get no errors when the file doesn't load - it just ignores the settings. However, given that this works (and gives me a REPL at minimal cost), I think I'll just stick to that.

**Comment by owickstrom** [comment]
OK, great! 👍
